### ISSUE TITLE
This issue is for group code review

### ISSUE THREAD

**Issue by Lasten-Ernest** [Hamayounali/hamayoun-portfolio#11]
- Good job so far!
- Very good and definitive html tags. 

- However, you have used 2 background-color values on CSS file line number 358. 
-Kindly remove the first one. This may trigger styling error during styling testing.

- Again, there is too much indentation space in your html file. Kindly use 2-space-bar space for indentation. This makes the code look smart and professional.

**Comment by Hamayounali** [comment]
Thank you, Mr. Ernest, I have noted your comments and I will do it acordingly.
