### ISSUE TITLE
Group code review

### ISSUE THREAD

**Issue by Lasten-Ernest** [Hamayounali/hamayoun-portfolio#6]
This issue is for group code review on the pull request by Hamayounali

**Comment by Lasten-Ernest** [comment]
There is too much indentation space on the <li>. Use 2 space-bar space for indentation. This looks nice and neat.

**Comment by elhamatokhi** [comment]
Great job so far!

- Clean and well-organized code.
- Nice CSS styles.
- Kindly have more descriptive commits. It will help your code seem more professional.
